#!/bin/bash
sudo apt-get update
sudo apt install python3
sudo apt-get update
sudo apt-get -y install python3-pip
sudo pip3 install numpy
sudo pip3 install launchpadlib
sudo pip3 install firebase_admin